Repository TINF18AI2/Vorlesungsplan, pull requests merged in 2019-12, with the labels that each got.

#25 updated contributing guidelines
  CONTRIBUTING.md
Labels: maintenance

#27 Feature/time estimation
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/EstimateTimeLeft.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/TimeUntilUniEnd.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#31 Feature/change icon
  app/src/main/ic_home-web.png
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/ListItemConverter.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/LoadPlanObserver.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/LoadWeekDataAsyncTask.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/PlanAnalyser.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/time_estimation/TimeEstimator.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/time_estimation/TimeEstimatorAsyncTask.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/MainActivity.kt
  app/src/main/res/drawable-anydpi/ic_home.xml
  app/src/main/res/drawable-hdpi/ic_home.png
  app/src/main/res/drawable-mdpi/ic_home.png
  app/src/main/res/drawable-xhdpi/ic_home.png
  app/src/main/res/drawable-xxhdpi/ic_home.png
  app/src/main/res/layout/content_main.xml
  app/src/test/java/com/tinf18ai2/vorlesungsplan/ObservableTest.kt
Labels: enhancement

#32 Cleaned code
  app/src/androidTest/java/com/tinf18ai2/vorlesungsplan/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/PlanAnalyser.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/time_estimation/TimeEstimator.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/time_estimation/TimeEstimatorAsyncTask.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/models/VorlesungsplanItem.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/models/Vorlesungstag.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/MainActivity.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/VorlesungsplanAdapter.kt
  app/src/main/res/drawable-anydpi/ic_arrow_left_white.xml
  app/src/main/res/drawable-anydpi/ic_arrow_right_white.xml
  app/src/main/res/drawable-anydpi/ic_home.xml
  app/src/main/res/drawable-anydpi/ic_reset_white.xml
  app/src/main/res/drawable-anydpi/ic_time_white.xml
  app/src/main/res/layout/content_main.xml
  app/src/test/java/com/tinf18ai2/vorlesungsplan/ExampleUnitTest.kt
  build.gradle
  fastlane/report.xml
  settings.gradle
Labels: maintenance

#33 Bug resolved, Restructured and fixed warnings
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/ListItemConverter.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/LoadPlanObserver.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/PlanAnalyser.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/time_estimation/TimeEstimator.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/time_estimation/TimeEstimatorAsyncTask.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/models/FABDataModel.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/models/VorlesungsPlanItemHolder.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/MainActivity.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/VorlesungsplanAdapter.kt
  app/src/test/java/com/tinf18ai2/vorlesungsplan/ObservableTest.kt
  app/src/test/java/com/tinf18ai2/vorlesungsplan/TimeEstimatorTest.kt
Labels: bug

#29 updated contributing
  CONTRIBUTING.md
Labels: maintenance

#40 Layout: Change week-buttons to FloatingActionButtons
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/MainActivity.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/RecyclerViewAdapterVorlesungsplanWeek.kt
  app/src/main/res/layout/content_main.xml
  app/src/main/res/layout/recycler_view_day_layout.xml
Labels: Layout

#42 Feature: Add rxKotlin for Observer-Pattern
  app/build.gradle
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/LoadPlanObserver.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/LoadWeekDataAsyncTask.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/lecture_plan_modules/PlanAnalyser.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/time_estimation/TimeEstimator.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/time_estimation/TimeEstimatorAsyncTask.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/MainActivity.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/RecyclerViewAdapterVorlesungsplanWeek.kt
Labels: feature

#47 Feature: Scroll to current day
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/MainActivity.kt
Labels: feature

#45 Feature: Add Countdown-View
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/tinf18ai2/vorlesungsplan/backend_services/time_estimation/TimeEstimator.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/models/FABDataModel.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/CountdownActivity.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/MainActivity.kt
  app/src/main/res/drawable-anydpi/ic_fullscreen.xml
  app/src/main/res/drawable-hdpi/ic_fullscreen.png
  app/src/main/res/drawable-mdpi/ic_fullscreen.png
  app/src/main/res/drawable-xhdpi/ic_fullscreen.png
  app/src/main/res/drawable-xxhdpi/ic_fullscreen.png
  app/src/main/res/layout/activity_countdown.xml
Labels: Layout, feature

#49 Feature: Implement ServiceFactory and Service interfaces
  app/src/main/java/com/tinf18ai2/vorlesungsplan/models/Vorlesungwoche.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/services/LecturePlanFetchService.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/services/LecturePlanService.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/services/LocaleService.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/services/ServiceFactory.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/services/TimeEstimationService.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/services/impl/LecturePlanFetchServiceImpl.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/services/impl/LecturePlanServiceImpl.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/services/impl/LocaleServiceImpl.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/services/impl/TimeEstimationServiceImpl.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/MainActivity.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/RecyclerViewAdapterVorlesungsplanDay.kt
  app/src/main/java/com/tinf18ai2/vorlesungsplan/ui/RecyclerViewAdapterVorlesungsplanWeek.kt
  app/src/test/java/com/tinf18ai2/vorlesungsplan/TimeEstimatorTest.kt
  app/src/test/java/com/tinf18ai2/vorlesungsplan/services/mock/LecturePlanFetchServiceMock.kt
Labels: feature
